### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by alecf**
Lots of dependencies updated:

 * jest/ts-jest/typescript - ts-jest needed to be updated, so these others had to as well
 * ~~serialize-javsacript - security vulnerability~~ (done already)
 * yargs - the reason I started this: yargs-parser has a minor prototype pollution issue

Tests seem to continue to pass. I see lots of errors while running the tests, but I'm pretty sure those are ttag testing if error conditions are caught?

### CODE REVIEW

**Comment by alecf** [comment]
oops, forgot to update my local `master` - doing that now and will force-push with conflicts resolved

**Comment by alecf** [comment]
(conflicts resolved, this is ready to go again)

**Comment by alecf** [comment]
@AlexMost Friendly ping!

**Comment by AlexMost** [comment]
Hi @alecf! Thanks for a great job!

**Comment by AlexMost** [comment]
new ver `1.8.5` is available :tada:

**Pull request merged**
