### PR TITLE
flow preset; decorators, class properties plugins

### PR DESCRIPTION
**Pull request by chrusart**
They are plugins I need to make it work in RN project, but also they're are kinda basic for react-native.

### CODE REVIEW

**Comment by AlexMost** [comment]
Thanks for the PR, I have just checked and seems like `ttag-cli` already extends your `.babelrc` config. There were some fixes done in this PR - https://github.com/ttag-org/ttag-cli/pull/45. 

Try version `1.3.0-1` with all your plugins included (but inside your project dir).

**Comment by chrusart** [comment]
I have, but still get errors about classProperties, and probably will about other syntax.

**Comment by chrusart** [comment]
What I have is a package.json script:
```"ttag_extract": "ttag extract ./src",```
after ```yarn install``` i just do ```yarn run tatg_extract``` and it seems that it doesn't see my .babelrc config.

**Comment by chrusart** [comment]
@AlexMost did you test with babel.config.js or .babelrc?

**Comment by AlexMost** [comment]
I have set up an example repository with `.babelrc` that adds decorators support - https://github.com/ttag-org/ttag-cli-babel-7-demo
I have checked those examples in a couple of environments and seems like they are working, can you check them?

**Comment by chrusart** [comment]
Yes, it works, it seems that it should take project .babelrc plugins, maybe some ordering.
I still have old babel packages in node_packades installed by other dependencies, maybe that causing problems.
here is my .babelrc:
```
{
  "presets": [
    "@babel/preset-flow"
  ],
  "plugins": [
    "@babel/plugin-transform-block-scoping",
    "@babel/plugin-transform-flow-strip-types",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    [
      "@babel/plugin-proposal-class-properties",
      { "loose": true },
    ],
    ["@babel/plugin-transform-computed-properties"],
    ["@babel/plugin-transform-destructuring"],
    ["@babel/plugin-transform-function-name"],
    ["@babel/plugin-transform-literals"],
    ["@babel/plugin-transform-parameters"],
    ["@babel/plugin-transform-shorthand-properties"],
    ["@babel/plugin-transform-react-jsx"],
    ["@babel/plugin-transform-regenerator"],
    ["@babel/plugin-transform-sticky-regex"],
    ["@babel/plugin-transform-unicode-regex"],
    [
      "@babel/plugin-transform-modules-commonjs",
      {
        "strict": false,
        "strictMode": false,
        "allowTopLevelThis": true,
      },
    ],
    "@babel/plugin-transform-arrow-functions",
    "@babel/plugin-transform-classes",
    ["@babel/plugin-transform-for-of", { "loose": true}],
    "@babel/plugin-transform-spread",
    [
      "@babel/plugin-transform-template-literals",
      {"loose": true},
    ],
    "@babel/plugin-transform-exponentiation-operator",
    "@babel/plugin-transform-object-assign",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-transform-react-display-name",
    "relay",
    "idx"
  ]
}
```

**Comment by chrusart** [comment]
I will close this PR soon as it was just to show what works for me, and it was before I knew that project .babelrc is taken too for cli.

**Comment by AlexMost** [comment]
If you would like you can add a reproduce case to https://github.com/ttag-org/ttag-cli-babel-7-demo and I will try to investigate deeper.

**Comment by chrusart** [comment]
Ok, found guilty.
We added ```package.json``` in ```src``` to access packages using ```src/...```
```
{
  "name": "src"
}
```
now I'm trying to make it work with it, if I delete this file, everything is working.
For now I tried to add .babelrc as well in src, no success, add all babel dependencies to ```src/package.json```, no success. Will try to make it work and come back with results.

**Comment by chrusart** [comment]
It is surely about how babel 7 resolves configs:
https://babeljs.io/docs/en/config-files
Simple reproduction is to put package.json into src folder containing:
```
{
  "name": "src"
}
```
demo project will not extract.

**Comment by chrusart** [comment]
For now ```babel.config.js``` works in demo with package.json in src:
```
const babelPluginDecorators = require('@babel/plugin-proposal-decorators')

module.exports = function(api) {
  api.cache(true);

  return {
    plugins: [
        [babelPluginDecorators, { "legacy": true } ]
    ]
  };
}
```

**Comment by AlexMost** [comment]
have just created the same example - https://github.com/ttag-org/ttag-cli-babel-7-demo/pull/1 :)

**Comment by chrusart** [comment]
Hehe :) Thanks!

**Comment by AlexMost** [comment]
Nice catch btw, thanks for investigating it. Going to add that case to docs.

**Comment by chrusart** [comment]
One more thing (yarn, RN):
```
  "resolutions": {
    "ttag-cli/@babel/core": "7.0.0-beta.47",
    "ttag-cli/@babel/generator": "7.0.0-beta.47",
    "ttag-cli/@babel/preset-react": "7.0.0-beta.47",
    "ttag-cli/@babel/template": "7.0.0-beta.47"
  },
```
to match RN babel versions exactly (error otherwise):
```Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null```
, until .57 come out.

**Comment by chrusart** [comment]
@AlexMost I guess you need some @babel/... dependencies for tests,
```
"devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
....
```
and probably to avoid babel version mismatch this should work, right?
```

  "peerDependencies": {
    "@babel/core": "7.x",
    "@babel/generator": "7.x",
    "@babel/preset-react": "7.x",
    "@babel/template": "7.x"
  },
```

**Comment by AlexMost** [comment]
`@AlexMost I guess you need some @babel/... dependencies for tests,`

Not sure that we should duplicate in devDependencies something that is already installed as a `dependencies`.

`and probably to avoid babel version mismatch this should work, right?`

CLI already installs `@babel/core` as it's dependency. As I understood, your suggestion is to move it to `peerDependency`?

As for `babel-plugin-ttag` we should add `@babel/core: 7.x` as a `peerDependency`, because it relies on the newer version but doesn't require it.

**Pull request closed without merging**
