### PR TITLE
Possibility to pass sortByMsgid option to extract/merge/update

### PR DESCRIPTION
**Pull request by AlexMost**
Issue - https://github.com/ttag-org/ttag-cli/issues/24
- [x] Add possibility to pass `sortByMsgid` to update and extract commands.
- [x] Test coverage for this option for update and extract.
- [ ] Add `sortByMsgid` option to the `merge` method.
- [ ] Test coverage for the merge.

### CODE REVIEW

**Comment by andrejpavlovic** [comment]
Perhaps just merging the sortByMsgId support for extract command is good enough to start?

**Comment by AlexMost** [comment]
Hi @andrejpavlovic! I thought that nobody needs that feature except me) Ok, will try to merge this ASAP.

**Comment by andrejpavlovic** [comment]
Any progress with this? For now I'm just using a branch built based on this pull request:
https://github.com/allboatsrise/ttag-cli/tree/sort-by-msgid-opt-build

**Comment by AlexMost** [comment]
the new version is available `1.7.23`. Let me know if that works for you. Sorry for the late merge.

**Pull request merged**
